# Generated by Django 2.2.9 on 2020-01-24 18:22

import app.core.models.enum
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_platform_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform',
            field=django_enumfield.db.fields.EnumField(default=1, enum=app.core.models.enum.PlatformType),
        ),
    ]
